---

- name: Show journalctl -e
  ansible.builtin.command: >-
    journalctl -e --lines 200 --no-pager
  changed_when: false
  register: testing_command_output
  tags:
    - troubleshooting
  failed_when: false

- name: Show journalctl -e
  ansible.builtin.debug:
    var: testing_command_output.stdout_lines
  tags:
    - troubleshooting

- name: Show journalctl -ue rke2-server
  ansible.builtin.command: >-
    journalctl -eu rke2-server --lines 200 --no-pager
  changed_when: false
  register: testing_command_output
  tags:
    - troubleshooting
  failed_when: false

- name: Show journalctl -ue rke2-server
  ansible.builtin.debug:
    var: testing_command_output.stdout_lines
  tags:
    - troubleshooting

- name: Show rke2 config file
  ansible.builtin.command: >-
    cat /etc/rancher/rke2/config.yaml
  changed_when: false
  register: testing_command_output
  tags:
    - troubleshooting
  failed_when: false

- name: Show rke2 config file
  ansible.builtin.debug:
    var: testing_command_output.stdout_lines
  tags:
    - troubleshooting
