---

- name: Add manifest addons files
  ansible.builtin.copy:
    src: "{{ manifest_config_file_path }}"
    dest: "/var/lib/rancher/rke2/server/manifests/"
    mode: '0640'
    owner: root
    group: root
