---

- name: Generate config.yml on other nodes
  ansible.builtin.include_tasks: config.yml

- name: Does config file already have server token?  # noqa command-instead-of-shell
  ansible.builtin.command: 'grep -i "^token:" /etc/rancher/rke2/config.yaml'
  register: server_token_check
  failed_when: server_token_check.rc >= 2
  changed_when: false

- name: Add token to config.yaml
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ hostvars[groups['rke2_servers'][0]].rke2_config_token }}"
    state: present
    insertbefore: BOF
  when:
    - '"token:" not in server_token_check.stdout'
  notify: "Restart {{ service_name }}"

- name: Does config file already have server url?  # noqa command-instead-of-shell
  ansible.builtin.command: 'grep -i "^server:" /etc/rancher/rke2/config.yaml'
  register: server_url_check
  failed_when: server_url_check.rc >= 2
  changed_when: false

- name: Add server url to config file
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ kubernetes_api_server_host }}:9345"
    state: present
    insertbefore: BOF
  when:
    - '"server:" not in server_url_check.stdout'
  notify: "Restart {{ service_name }}"

- name: Wait for rke2
  ansible.builtin.include_tasks: wait_for_rke2.yml
