---

- name: Wait for node-token
  ansible.builtin.wait_for:
    path: "{{ rke2_data_dir }}/server/node-token"
  delegate_to: "{{ token_source_node }}"
  tags: ["configure"]

- name: Read node-token from master
  ansible.builtin.slurp:
    src: "{{ rke2_data_dir }}/server/node-token"
  register: node_token
  delegate_to: "{{ token_source_node }}"
  tags: ["configure"]

- name: Store Master node-token
  ansible.builtin.set_fact:
    rke2_config_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
  delegate_to: "{{ token_source_node }}"
  tags: ["configure"]

- name: Set temp fact to store token config line
  ansible.builtin.set_fact:
    temp_token:
      token: "{{ rke2_config_token }}"
  tags: ["configure"]

- name: Update host_rke2_config fact to contain server line
  ansible.builtin.set_fact:
    host_rke2_config: "{{ temp_token | default({}) | ansible.builtin.combine((host_rke2_config | default({})), list_merge='prepend_rp') }}"
  tags: ["configure"]

- name: Set temp fact for api host
  ansible.builtin.set_fact:
    rke2_kubernetes_api_server_host: "{{ hostvars[token_source_node]['ansible_default_ipv4']['address'] }}"
  when:
    - rke2_kubernetes_api_server_host == ""
  tags: ["configure"]

- name: Set temp fact to store server config line with custom join server URL
  ansible.builtin.set_fact:
    temp_host_rke2_config:
      server: "https://{{ rke2_kubernetes_api_server_host }}:9345"
  tags: ["configure"]

- name: Update host_rke2_config fact to contain server line
  ansible.builtin.set_fact:
    host_rke2_config: "{{ temp_host_rke2_config | default({}) | ansible.builtin.combine((host_rke2_config | default({})), list_merge='prepend_rp') }}"
  tags: ["configure"]
