---

- name: Add /var/lib/rancher/rke2/bin to PATH
  ansible.builtin.lineinfile:
    dest: "/root/.bashrc"
    line: 'PATH=$PATH:/var/lib/rancher/rke2/bin'
    insertafter: EOF

- name: Symlink crictl config to /etc/crictl.yaml
  ansible.builtin.file:
    src: "/var/lib/rancher/rke2/agent/etc/crictl.yaml"
    dest: "/etc/crictl.yaml"
    state: link

- name: Create .kube directory in /root
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0750'

- name: Symlink kubectl config to /root/.kube/config
  ansible.builtin.file:
    src: "/var/lib/rancher/rke2/server/cred/admin.kubeconfig"
    dest: "/root/.kube/config"
    state: link
