---
- name: Create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes

- name: Add registry configuration file
  ansible.builtin.copy:
    src: "{{ registry_config_file_path }}"
    dest: "/etc/rancher/rke2/registries.yaml"
    mode: '0640'
    owner: root
    group: root
  when: caller_role_name == "server"
  notify: Restart rke2-server

- name: Add registry configuration file
  ansible.builtin.copy:
    src: "{{ registry_config_file_path }}"
    dest: "/etc/rancher/rke2/registries.yaml"
    mode: '0640'
    owner: root
    group: root
  when: caller_role_name == "agent"
  notify: Restart rke2-agent
