---

- name: "Calculate rke2 full version"
  when: ( install_rke2_version is not defined ) or ( install_rke2_version | length == 0 )
  block:
    - name: Stop if the provided is not valid
      ansible.builtin.fail:
        msg: "Provided channel is not valid"
      when: rke2_channel not in channels

    - name: Get full version name url
      ansible.builtin.uri:
        url: https://update.rke2.io/v1-release/channels/{{ rke2_channel }}
        follow_redirects: safe
        remote_src: true
      register: rke2_version_url

    - name: Set full version name
      ansible.builtin.shell: set -o pipefail && echo {{ rke2_version_url.url }} | sed -e 's|.*/||'
      register: rke2_full_version
      changed_when: false
      args:
        executable: /usr/bin/bash

- name: Set rke2_full_version fact
  ansible.builtin.set_fact:
    rke2_full_version: "{{ rke2_full_version.stdout if ((install_rke2_version is not defined) or (install_rke2_version|length == 0)) else install_rke2_version }}"  # yamllint disable-line rule:line-length

- name: Set dot version
  ansible.builtin.shell:
    cmd: set -o pipefail && echo {{ rke2_full_version }} | /usr/bin/cut -d'+' -f1
  register: rke2_version_dot_tmp
  changed_when: false
  args:
    executable: /usr/bin/bash

- name: Set rke2_version_dot fact
  ansible.builtin.set_fact:
    rke2_version_dot: "{{ rke2_version_dot_tmp.stdout }}"

- name: Set Maj.Min version
  ansible.builtin.shell:
    cmd: set -o pipefail && echo {{ rke2_full_version }} | /bin/awk -F'.' '{ print $1"."$2 }' | sed "s|^v||g"
  register: rke2_version_majmin_tmp
  changed_when: false
  args:
    executable: /usr/bin/bash

- name: Set rke2_version_majmin fact
  ansible.builtin.set_fact:
    rke2_version_majmin: "{{ rke2_version_majmin_tmp.stdout }}"

- name: Set RPM version
  ansible.builtin.shell:
    cmd: set -o pipefail && echo {{ rke2_full_version }} | sed -E -e "s/[\+-]/~/g" | sed -E -e "s/v(.*)/\1/"
  register: rke2_version_rpm_tmp
  changed_when: false
  args:
    executable: /usr/bin/bash

- name: Set rke2_version_rpm fact
  ansible.builtin.set_fact:
    rke2_version_rpm: "{{ rke2_version_rpm_tmp.stdout }}"

- name: Describe versions
  ansible.builtin.debug:
    msg:
      - "Full version, with revision indication: {{ rke2_full_version }}"
      - "Version without revision indication: {{ rke2_version_dot }}"
      - "Major and Minor Only: {{ rke2_version_majmin }}"
      - "RPM Version (tilde): {{ rke2_version_rpm }}"
