---

# This fixes known issue with NetworkManager
# https://docs.rke2.io/known_issues/#networkmanager

- name: Add NetworkManager fix to rke2-canal.conf
  blockinfile:
    path: /etc/NetworkManager/conf.d/rke2-canal.conf
    block: |
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:flannel*
    create: yes
    mode: 0600
  when: ansible_facts.services["NetworkManager.service"] is defined

- name: Does rke2-canal.conf exist
  stat:
    path: /etc/NetworkManager/conf.d/rke2-canal.conf
  register: rke2_canal_file

- name: Set rke2-canal.conf file permissions
  file:
    path: /etc/NetworkManager/conf.d/rke2-canal.conf
    mode: '0600'
    owner: root
    group: root
  when: rke2_canal_file.stat.exists

- name: Disable service nm-cloud-setup
  systemd:
    name: nm-cloud-setup.service
    enabled: no
    state: stopped
  when: ansible_facts.services["nm-cloud-setup.service"] is defined

- name: Disable nm-cloud-setup.timer unit
  systemd:
    name: nm-cloud-setup.timer
    state: stopped
    enabled: no
  when: ansible_facts.services["nm-cloud-setup.service"] is defined
