---
name: Ubuntu

on:
  pull_request:
  workflow_dispatch:

jobs:

  "_22_":
    uses: ./.github/workflows/reusable_integration_testing.yml
    with: 
      os: ubuntu22
      ssh_user: ubuntu
    secrets: inherit
  "_24_":
    uses: ./.github/workflows/reusable_integration_testing.yml
    with: 
      os: ubuntu24
      ssh_user: ubuntu
    secrets: inherit